name: CI - Film-o-metre

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  docker-build:
    name: Docker Build Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Test Docker Build
        run: |
          docker compose -f docker/docker-compose.yml build
          echo "Docker build successful"
      
      - name: Test Application
        run: |
          docker compose -f docker/docker-compose.yml up -d
          sleep 30
          curl -f http://localhost/api/film || exit 1
          docker compose -f docker/docker-compose.yml down

  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: SonarQube Scan
        uses: sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarqube.delpech.info
